package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import src.*;
import javax.swing.*;
import java.awt.event.*;

/**
 * Class Registrasi merupakan class untuk run program
 * @Author CloudNein
 * @Version 26/11/2022
 */

public class Registrasi extends javax.swing.JFrame implements ActionListener {

    // inisialisasi atribut
    public String nama;
    public String id;
    public double lamaMenginap;
    public Kamar kamar;
    public double harga;
    public double total;
    
    public Registrasi() {
        initComponents();
        nextButton.addActionListener(this);
        show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        judulLabel = new javax.swing.JLabel();
        namatext = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        lamaLabel = new javax.swing.JLabel();
        lamatext = new javax.swing.JTextField();
        comboJenis = new javax.swing.JComboBox<>();
        nextButton = new javax.swing.JButton();
        JenisLabel = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        judulLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judulLabel.setText("HOTEL TRAVEKOLA");
        getContentPane().add(judulLabel);
        judulLabel.setBounds(140, 20, 340, 70);

        namatext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatextActionPerformed(evt);
            }
        });
        getContentPane().add(namatext);
        namatext.setBounds(200, 120, 140, 30);

        namaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaLabel.setText("Nama");
        getContentPane().add(namaLabel);
        namaLabel.setBounds(80, 120, 85, 20);

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLabel.setText("Id");
        getContentPane().add(idLabel);
        idLabel.setBounds(80, 160, 85, 16);

        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        getContentPane().add(idText);
        idText.setBounds(200, 160, 140, 30);

        lamaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lamaLabel.setText("Lama Menginap");
        getContentPane().add(lamaLabel);
        lamaLabel.setBounds(80, 200, 120, 20);

        lamatext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamatextActionPerformed(evt);
            }
        });
        getContentPane().add(lamatext);
        lamatext.setBounds(200, 200, 140, 30);

        comboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Kamar Standard", "2.Kamar Superior", "3.Kamar Deluxe" }));
        comboJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJenisActionPerformed(evt);
            }
        });
        getContentPane().add(comboJenis);
        comboJenis.setBounds(200, 240, 140, 30);

        nextButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nextButton.setText("Next");
        getContentPane().add(nextButton);
        nextButton.setBounds(240, 310, 63, 22);

        JenisLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JenisLabel.setText("Jenis Kamar");
        getContentPane().add(JenisLabel);
        JenisLabel.setBounds(80, 240, 85, 16);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 594, 440);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 440);

        pack();
    }// </editor-fold>                        

    private void namatextActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    }                                        

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
    }                                      

    private void comboJenisActionPerformed(java.awt.event.ActionEvent evt) {                                           

        if (comboJenis.getSelectedIndex() == 0){
            Kamar kamar = new KamarStandard();
            harga = kamar.getharga();
        }
        else if (comboJenis.getSelectedIndex()==1){
            Kamar kamar = new KamarSuperior();
            harga = kamar.getharga();
        }
        else if (comboJenis.getSelectedIndex()==2){
            Kamar kamar = new KamarDeluxe();
            harga = kamar.getharga();
        }
    }                                          

    private void lamatextActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    }                                        

    public void actionPerformed (ActionEvent e){
        
        if (e.getSource()== nextButton ){
            nama = namatext.getText().trim();
            id = idText.getText().trim();
            String l = lamatext.getText().trim();
            lamaMenginap = Double.parseDouble(l);
            String next = "";
            next+="     PEMBAYARAN"+"\n\n";
            next+="Nama           : "+nama+"\n";
            next+="Id                 : "+id+"\n";
            next+="Jenis Kamar: "+comboJenis.getItemAt(comboJenis.getSelectedIndex())+"\n";
            next+="Total            : "+ lamaMenginap * harga+"\n";
            JOptionPane.showMessageDialog(null, next, "PEMBAYARAN",
            JOptionPane.INFORMATION_MESSAGE);
        } 
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BG;
    private javax.swing.JLabel JenisLabel;
    private javax.swing.JComboBox<String> comboJenis;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JLabel lamaLabel;
    private javax.swing.JTextField lamatext;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namatext;
    private javax.swing.JButton nextButton;
    // End of variables declaration                   
}
